C1:
	gcc -o changing_time changing_time.c
	gcc -o check_time check_time.c
	gcc -o correct_time correct_time.c
	gcc -o udpserver udpserver.c
	gcc -o sic sic.c `gsl-config --cflags --libs`
	gcc -o sic_extended sic_extended.c `gsl-config --cflags --libs`
